2017-11-27 10:36:13,937 WARNING pcs.get_user_uk(), failed to parse uk, http://yun.baidu.com
2017-11-27 10:36:13,938 ERROR Failed to get user avatar: None, None
2017-11-27 10:36:19,478 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:19,639 DEBUG add view history: /
2017-11-27 10:36:19,710 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:19,966 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:20,173 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:20,439 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:20,592 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:20,946 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:21,053 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:21,294 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:21,523 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:22,081 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:22,081 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:22,194 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:22,379 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:22,566 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:22,755 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:23,263 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:23,267 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:23,480 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:23,701 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:23,869 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:24,075 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:24,417 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:24,798 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:25,058 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:25,310 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:25,509 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:25,723 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:25,894 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:26,087 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:26,282 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:26,608 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:26,806 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:27,004 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:27,244 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:27,642 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:27,721 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:27,960 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:28,137 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:28,383 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:28,589 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:28,802 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:29,048 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:29,286 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:29,472 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:29,661 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:29,848 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:30,087 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:30,088 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:30,360 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:30,522 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:30,754 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:30,933 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:32,256 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:32,490 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:32,833 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:33,029 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:33,239 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:33,523 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:33,733 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:33,939 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:34,156 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:34,316 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:34,503 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:34,721 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:34,938 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:35,226 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:35,513 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:35,813 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:36,057 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:36,277 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:36,545 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:36,761 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:36,946 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:37,179 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:37,426 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:37,639 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:37,970 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:38,153 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:38,423 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:38,629 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:38,871 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:39,109 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:39,636 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:39,831 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:40,169 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:40,422 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:40,638 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:40,928 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:41,268 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:41,603 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:41,812 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:42,071 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:42,291 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:42,528 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:42,728 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/net.py", line 114, in urlopen
    req = opener.open(url, data=data, timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] 连接被对方重设

2017-11-27 10:36:43,111 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:43,327 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:43,538 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:43,747 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:43,982 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:36:44,297 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-27 10:37:10,511 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/net.py", line 114, in urlopen
    req = opener.open(url, data=data, timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

2017-11-30 19:44:50,356 WARNING pcs.get_user_uk(), failed to parse uk, http://yun.baidu.com
2017-11-30 19:44:50,368 ERROR Failed to get user avatar: None, None
2017-11-30 19:45:05,238 DEBUG add view history: /
2017-11-30 19:45:05,425 ERROR 图片.on_load: {'errno': 31034, 'request_id': 7742297244423721271}, None
2017-11-30 19:45:05,557 ERROR 音乐.on_load: {'errno': 31034, 'request_id': 7742297253965824751}, None
2017-11-30 19:45:05,639 ERROR 视频.on_load: {'errno': 31034, 'request_id': 7742297266415727860}, None
2017-11-30 19:45:05,678 WARNING pcs.get_user_uk(), failed to parse uk, http://yun.baidu.com
2017-11-30 19:45:05,749 ERROR 其它.on_load: {'errno': 31034, 'request_id': 7742297256720726940}, None
2017-11-30 19:45:05,819 ERROR 文档.on_load: {'errno': 31034, 'request_id': 7742297252446005579}, None
2017-11-30 19:45:05,940 ERROR 文档.on_load: {'errno': 31034, 'request_id': 7742297377765158825}, None
2017-11-30 19:45:06,029 ERROR 视频.on_load: {'errno': 31034, 'request_id': 7742297390150064289}, None
2017-11-30 19:45:06,107 ERROR 图片.on_load: {'errno': 31034, 'request_id': 7742297387113393680}, None
2017-11-30 19:45:06,138 ERROR Failed to get user avatar: None, None
2017-11-30 19:45:06,388 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-30 19:45:10,265 DEBUG add view history: /黑马程序员_历经5年锤炼(适合初学者入门的Java基础视频)
2017-11-30 19:45:11,877 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-30 19:45:21,277 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 147, in update_image
    icon_size)
GLib.GError: gdk-pixbuf-error-quark: 分析 JPEG 图像文件时出错(Not a JPEG file: starts with 0x7b 0x22) (0)

2017-11-30 19:45:41,359 DEBUG DownloadBatch.get_req: 0, 34641433
2017-11-30 19:45:41,362 DEBUG DownloadBatch.get_req: 34641434, 69282867
2017-11-30 19:45:41,366 DEBUG DownloadBatch.get_req: 69282868, 103924301
2017-11-30 19:45:41,369 DEBUG DownloadBatch.get_req: 103924302, 138565735
2017-11-30 19:45:41,372 DEBUG DownloadBatch.get_req: 138565736, 173207169
2017-11-30 19:45:41,378 DEBUG DownloadBatch.get_req: 173207170, 207848603
2017-11-30 19:45:41,382 DEBUG DownloadBatch.get_req: 207848604, 242490037
2017-11-30 19:45:41,385 DEBUG DownloadBatch.get_req: 242490038, 277131476
2017-11-30 19:45:41,438 DEBUG DownloadBatch.get_req: 0, 31160664
2017-11-30 19:45:41,447 DEBUG DownloadBatch.get_req: 31160665, 62321329
2017-11-30 19:45:41,448 DEBUG DownloadBatch.get_req: 62321330, 93481994
2017-11-30 19:45:41,449 DEBUG DownloadBatch.get_req: 93481995, 124642659
2017-11-30 19:45:41,461 DEBUG DownloadBatch.get_req: 124642660, 155803324
2017-11-30 19:45:41,464 DEBUG DownloadBatch.get_req: 155803325, 186963989
2017-11-30 19:45:41,470 DEBUG DownloadBatch.get_req: 186963990, 218124654
2017-11-30 19:45:41,481 DEBUG DownloadBatch.get_req: 218124655, 249285323
2017-11-30 19:45:41,524 DEBUG DownloadBatch.get_req: 0, 38560726
2017-11-30 19:45:41,528 DEBUG DownloadBatch.get_req: 38560727, 77121453
2017-11-30 19:45:41,532 DEBUG DownloadBatch.get_req: 77121454, 115682180
2017-11-30 19:45:41,535 DEBUG DownloadBatch.get_req: 115682181, 154242907
2017-11-30 19:45:41,536 DEBUG DownloadBatch.get_req: 154242908, 192803634
2017-11-30 19:45:41,542 DEBUG DownloadBatch.get_req: 192803635, 231364361
2017-11-30 19:45:41,548 DEBUG DownloadBatch.get_req: 231364362, 269925088
2017-11-30 19:45:41,555 DEBUG DownloadBatch.get_req: 269925089, 308485817
2017-11-30 19:45:41,636 DEBUG DownloadBatch.get_req: 0, 222980
2017-11-30 19:45:41,773 DEBUG DownloadBatch.get_req: 0, 41225886
2017-11-30 19:45:41,776 DEBUG DownloadBatch.get_req: 41225887, 82451773
2017-11-30 19:45:41,789 DEBUG DownloadBatch.get_req: 82451774, 123677660
2017-11-30 19:45:41,802 DEBUG DownloadBatch.get_req: 123677661, 164903547
2017-11-30 19:45:41,804 DEBUG DownloadBatch.get_req: 164903548, 206129434
2017-11-30 19:45:41,805 DEBUG DownloadBatch.get_req: 206129435, 247355321
2017-11-30 19:45:41,807 DEBUG DownloadBatch.get_req: 247355322, 288581208
2017-11-30 19:45:41,809 DEBUG DownloadBatch.get_req: 288581209, 329807097
2017-11-30 19:45:43,437 ERROR DownloadBatch, block is empty: 164903548, 164903548, 206129434, 0
2017-11-30 19:45:44,536 DEBUG DownloadBatch.get_req: 0, 30237494
2017-11-30 19:45:44,537 DEBUG DownloadBatch.get_req: 30237495, 60474989
2017-11-30 19:45:44,538 DEBUG DownloadBatch.get_req: 60474990, 90712484
2017-11-30 19:45:44,539 DEBUG DownloadBatch.get_req: 90712485, 120949979
2017-11-30 19:45:44,540 DEBUG DownloadBatch.get_req: 120949980, 151187474
2017-11-30 19:45:44,541 DEBUG DownloadBatch.get_req: 151187475, 181424969
2017-11-30 19:45:44,541 DEBUG DownloadBatch.get_req: 181424970, 211662464
2017-11-30 19:45:44,542 DEBUG DownloadBatch.get_req: 211662465, 241899961
2017-11-30 19:46:05,326 DEBUG DownloadBatch.get_req: 0, 35051102
2017-11-30 19:46:05,327 DEBUG DownloadBatch.get_req: 35051103, 70102205
2017-11-30 19:46:05,330 DEBUG DownloadBatch.get_req: 70102206, 105153308
2017-11-30 19:46:05,337 DEBUG DownloadBatch.get_req: 105153309, 140204411
2017-11-30 19:46:05,340 DEBUG DownloadBatch.get_req: 140204412, 175255514
2017-11-30 19:46:05,345 DEBUG DownloadBatch.get_req: 175255515, 210306617
2017-11-30 19:46:05,346 DEBUG DownloadBatch.get_req: 210306618, 245357720
2017-11-30 19:46:05,351 DEBUG DownloadBatch.get_req: 245357721, 280408824
2017-11-30 19:47:14,838 ERROR DownloadBatch, block is empty: 155189248, 154242908, 192803634, 0
2017-11-30 19:47:30,631 ERROR DownloadBatch, block is empty: 63430674, 62321330, 93481994, 0
2017-11-30 19:47:54,091 ERROR DownloadBatch, block is empty: 36160519, 35051103, 70102205, 0
2017-11-30 19:47:55,315 DEBUG DownloadBatch.get_req: 0, 21162834
2017-11-30 19:47:55,315 DEBUG DownloadBatch.get_req: 21162835, 42325669
2017-11-30 19:47:55,323 DEBUG DownloadBatch.get_req: 42325670, 63488504
2017-11-30 19:47:55,329 DEBUG DownloadBatch.get_req: 63488505, 84651339
2017-11-30 19:47:55,332 DEBUG DownloadBatch.get_req: 84651340, 105814174
2017-11-30 19:47:55,336 DEBUG DownloadBatch.get_req: 105814175, 126977009
2017-11-30 19:47:55,339 DEBUG DownloadBatch.get_req: 126977010, 148139844
2017-11-30 19:47:55,343 DEBUG DownloadBatch.get_req: 148139845, 169302679
2017-11-30 19:47:55,352 DEBUG DownloadBatch.get_req: 169302680, 190465514
2017-11-30 19:47:55,355 DEBUG DownloadBatch.get_req: 190465515, 211628356
2017-11-30 19:47:56,555 ERROR DownloadBatch, block is empty: 190465515, 190465515, 211628356, 0
2017-11-30 19:47:58,051 DEBUG DownloadBatch.get_req: 0, 21584186
2017-11-30 19:47:58,052 DEBUG DownloadBatch.get_req: 21584187, 43168373
2017-11-30 19:47:58,059 DEBUG DownloadBatch.get_req: 43168374, 64752560
2017-11-30 19:47:58,065 DEBUG DownloadBatch.get_req: 64752561, 86336747
2017-11-30 19:47:58,068 DEBUG DownloadBatch.get_req: 86336748, 107920934
2017-11-30 19:47:58,069 DEBUG DownloadBatch.get_req: 107920935, 129505121
2017-11-30 19:47:58,073 DEBUG DownloadBatch.get_req: 129505122, 151089308
2017-11-30 19:47:58,083 DEBUG DownloadBatch.get_req: 151089309, 172673495
2017-11-30 19:47:58,084 DEBUG DownloadBatch.get_req: 172673496, 194257682
2017-11-30 19:47:58,087 DEBUG DownloadBatch.get_req: 194257683, 215841875
2017-11-30 19:48:05,709 DEBUG DownloadBatch.get_req: 1048576, 35051102
2017-11-30 19:48:05,710 DEBUG DownloadBatch.get_req: 36160519, 70102205
2017-11-30 19:48:05,713 DEBUG DownloadBatch.get_req: 71150782, 105153308
2017-11-30 19:48:05,716 DEBUG DownloadBatch.get_req: 106201885, 140204411
2017-11-30 19:48:05,722 DEBUG DownloadBatch.get_req: 141252988, 175255514
2017-11-30 19:48:05,723 DEBUG DownloadBatch.get_req: 176304091, 210306617
2017-11-30 19:48:05,728 DEBUG DownloadBatch.get_req: 211355194, 245357720
2017-11-30 19:48:05,729 DEBUG DownloadBatch.get_req: 246406297, 280408824
2018-01-16 21:30:38,550 DEBUG refresh vcode url: https://passport.baidu.com/v2/?reggetcodestr&token=b52bed8f6bb8ab10f71d1efbd7788f42&tpl=pp&apiver=v3&tt=1516109438550&fr=ligin&vcodetype=6bad3Yu1wAv5Q+d6daEipKED2fWBO9dGiILMX2Oc8bgAMEzLNtmontECWgKlsCG/eqVUA46sJ3olLB4EaVK3QOyQl4Qv0dToVF6j
2018-01-16 21:30:38,953 DEBUG refresh vcode: {"errInfo":{        "no": "0"    },    "data": {        "verifyStr" : "jxG0307c14d0a77c10c0260151144017e316dd6430713017f15",        "verifySign" : "217f954984"    },    "traceid": ""}
2018-01-16 21:30:38,954 DEBUG refresh vcode: {'errInfo': {'no': '0'}, 'data': {'verifyStr': 'jxG0307c14d0a77c10c0260151144017e316dd6430713017f15', 'verifySign': '217f954984'}, 'traceid': ''}
2018-01-16 21:30:58,558 DEBUG refresh vcode url: https://passport.baidu.com/v2/?reggetcodestr&token=922e4147ff96ae97d9efd8eaeaa329b9&tpl=pp&apiver=v3&tt=1516109458558&fr=ligin&vcodetype=6b595w53dBRz0mF6727G3v6CxnkugL3HjFWRCelzCL/neJqFErMob0ryuBEEibTjchHZGeF3gz7WKvSOGyVfYzNwQYFxw7GT16t+
2018-01-16 21:30:58,920 DEBUG refresh vcode: {"errInfo":{        "no": "0"    },    "data": {        "verifyStr" : "jxG8f06c14d0a1ee24a027c15bb4301837e6edc9807a2017b46",        "verifySign" : "4198241a6e"    },    "traceid": ""}
2018-01-16 21:30:58,922 DEBUG refresh vcode: {'errInfo': {'no': '0'}, 'data': {'verifyStr': 'jxG8f06c14d0a1ee24a027c15bb4301837e6edc9807a2017b46', 'verifySign': '4198241a6e'}, 'traceid': ''}
2018-01-16 21:42:22,086 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxGb107c14e0a2cc160023015b04301227f96f443072d047ef8', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': '736dZLRjo7u51rfPPV9tGEnYzRN4bl4n//vCQ/6PBVmV8kYEF4ngzWfMlVCc8HOoOSKPR/LqKovx/geQhewpampymCLS0koM/ZDTxRsjzxCayN+F13ukUR5da/qjO7xJoKTBV7RQsw7Lp0E+D3O9S3A47GTsGx/DPh7737AjAlmSU1fnPx9d/HO0t5SW2qGL5czSOXRzU7V6b2HdrIltDH/7xemDXgaDyiTOH30T3BoTaDkFeXPnRzaAng3AfnTLtW+FvKAf1qWjqL1TDPi1bZyzGI9ErdZCZUyqJH/efcTDGGxjZJU/X7A3mVYjbWid9sl5unfndKAGYccvCM2tm0FhIPUPxwN24fBC4jzSDF3AN4fbe1GS9567dpzLGioBdDS+SMkIhuMFeD5vgTbdGYjSiVsOOIsxS4zqjL0RkopIdRrG/F1LCAplUzwKrJgGHxEaWJejWJzFqUro', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=a7182fdf0f580f053489197fbb206c3a&lstr=7b96HY4hdsz6Qd9BMKlqPnMF7E3J9UXjH2S335cwpIMYTdWd8v%2FUPcIF6%2B1ONy%2Fkkei8772NCUWkjfZf4UEC&traceid=', 'vcodetype': '3ffbcke0K8yFnQBlqrCrFZc7\\/BAiMncz8GBBRmTF4RDYq38\\/VJCy9FPQ0yQgi3VDmuOmBa\\/bZyvRTEzc3vFWMfQO6owC8KQBI4Yl', 'lstr': '7b96HY4hdsz6Qd9BMKlqPnMF7E3J9UXjH2S335cwpIMYTdWd8v/UPcIF6+1ONy/kkei8772NCUWkjfZf4UEC', 'ltoken': 'a7182fdf0f580f053489197fbb206c3a', 'realnameverifyemail': '0'}), None
2018-01-16 21:42:33,975 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxG2507c14e0af2c1a0024d15fe4301247f97fc4307b9047ead', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': '2b66dwhJpU3ZJxxoUg318jwylGhoYkHdG2xKMn4jPa3NaYMvWvhFqAAknd5jOgrmbGqGg0cS8dEryyU9Rxa6f0KCvtJyEqBa3Xmsq7haRun9nG8Nq+7+xnp118jLjdiO5PrXORHI6zafLueNb3XpfQ3U9X6rdbuDl6LPiXwqPaIvETKV+m12utdWj+jH6ks6OvHB33osXwBL4EvTYQFB0kPQvcGMwdkNh+zmoU0dq9NIYl8m4wF8UY0hQI5d1HXqXnozuUbApqHOVtYQti1jeI9eX+wIF9aZyYCEgH6JVeESwLY/zcyofWYMrjWex8jyFMLZVFz2bGYsMdCUmFzHj/l9GkJ/J33KY2u5esajlTM5sbXlS0WmDJUzUJ795fuQ8dTinkUe1NaSazggon99OwZ6hljRpt2/qx3LPjRKwURH0TlYKNjwtoXw9YptNx3d9si4Biz+OYtyPmDztA', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=5da9249edc387b92337da5540cd50940&lstr=a84buWox7l8LusEF132kcXWw3eZT8r1Tr5sxtojqNAY2SUamBMR1TOuuRL0A3ATuqYD5Tf%2FRwm2MRj2oOq2p&traceid=', 'vcodetype': 'ae5aLtNKWwts42pOG 8fhjL7D1M2Wa HQEKiGleti9CwnobjXTLTONfOpRf8wqWKw3CpnsafeJQzCT3r4\\/4oEUp NF6qbz kD2HH', 'lstr': 'a84buWox7l8LusEF132kcXWw3eZT8r1Tr5sxtojqNAY2SUamBMR1TOuuRL0A3ATuqYD5Tf/Rwm2MRj2oOq2p', 'ltoken': '5da9249edc387b92337da5540cd50940', 'realnameverifyemail': '0'}), None
2018-01-16 21:42:52,704 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxGfe07c14e0a4ac18302b015304301297f9841430798047ecb', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': 'bf7c5SxQJTwDsPAwN2ZnDgDC9imQL/JjfIHEqz68+zxiCnKA5ypge+b/Ygtt9JQz6UUbJky8BwYXDMlMnqB6RTt7OJBhITcJYUOIwUGA6n+EBXn2M446lRWgbqxFQnbrO6ou0cSQ8smGviiLGs1Rj1DYqv0WUgG1CdYx6ulwI/VjbVsaDV8pOHiGYryY7uxRwQP2SIIKt8l9foFQg+qpG7hqSpDB8vE/tcb30iSr/R4BRaW35ubJB2fb4VCCSpNFUTqdE/9MG9/AKupqhnu/4/x8rZCAgfBMB+hdudfetzP36D+Qr6W6YAA+r7++35KuxATx1BMcgZpXts2kU7Ud7U+eT7LIkavH3BG9jhUnuJ9ElDmO1OYN3eGRWSo1uRjRFy9ZFeZHbv9ot3Q60rJsSK7yfpvcQzWdeFw2uQjTrMLhtOz9v+tTlykMw5+cpE8BvLnTF++vn6s', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=ddd04913df341d5efa885a773e8202db&lstr=e0c168GR7oHB0uXPgGLKHdC0XTQxhSfh8ZtbrqAF3zM70YJ9nS01R3Xb3Rj27eBC7slt22Rx0b0IdSCKuz%2Bk&traceid=', 'vcodetype': 'df65R9ORqstqdYTMQgSzB6Hz5bZXAp9qP7f1jH0wrNicWC95JphX1tzyhU6MC5za33g5RwxmHAa7x3qs2ugRP HYAH0xjAJZsJ J', 'lstr': 'e0c168GR7oHB0uXPgGLKHdC0XTQxhSfh8ZtbrqAF3zM70YJ9nS01R3Xb3Rj27eBC7slt22Rx0b0IdSCKuz+k', 'ltoken': 'ddd04913df341d5efa885a773e8202db', 'realnameverifyemail': '0'}), None
2018-01-16 21:47:33,489 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxG1006c14e0aaae2cb0243155043016a7ea9699807e8047b87', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': '98a5AxV3ZYrsaAzaKkZlh55Lr9EtpfONW72+iCYepxyaMiBBAJX6n/WeGpZoDjxrjuEIxK7+cy6JnjcwpOQOe01uMvAoQ8VRwxKcodI7Z/mHLZv2KWyubq4CIw84QFsyUdw5aCZG6XbJI4jbvJFoYmQPYLbPIFzbZohBa7JqG8y7HNhC8xXSR7hp30eqVMMT03TCN97VjPYkiHUhYasbkJYWi3pjmUDiTcUA58p+aOrP/hfVVfV9Wu0lSFQwCPXonyL5e0x3LEGybO8lPZGIP45TRBowc/veIWZiVN5piECDUVbkiJBWM4JkkdMarvpf0GVDroLS+pyPI6rlewh5vhBdP6Z0ojRxNM5FO4dqRD+HKOjbChF37mkwJ3ZZEPscMYAu9ECoUfGvZXP1O1mnAOqRucRKNnFIW6PAErouXJaemYCXPpZUhRizE/GV0hqu6T2Rd2qSQr0', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=15365cdcc9604715be7eb370f408daeb&lstr=bc38mYDSbxtkPsbY9a8Gs2Y4V2EwuTASDNU2a26WOfqT4m3k%2B%2FoqmDbpt1AurMTzNpbpM6QVBFuiXOeQeAUM&traceid=', 'vcodetype': '72f8u0bhB Hshvvr46inUqvWRHMm N0WNUoBWICFrh3jwz2QVuWnlNBuJTmT999kRarGou1QM8xwcrOJ54F2bGPXjxiF PMp Wlp', 'lstr': 'bc38mYDSbxtkPsbY9a8Gs2Y4V2EwuTASDNU2a26WOfqT4m3k+/oqmDbpt1AurMTzNpbpM6QVBFuiXOeQeAUM', 'ltoken': '15365cdcc9604715be7eb370f408daeb', 'realnameverifyemail': '0'}), None
2018-01-16 21:48:17,722 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxG4707c14e0af7c12702e815e74301747fac3543072a047e2a', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': '55c8b8y0y7Nrza37RimsG1jTh3xU6ndQtB89ZfyTXrsSFgOXXj+OGSFwii1LnIl1kS92T9pvpvgp1ChifURXK2R0y5LzLYPpR4TKTepoFFlBgAc10qN6sueQR4/XaAKEZBdz+2gxFLeXbyAAMQP+f6uDD3LL1r537OZhWo1ZZeYE1fBecCDyH4NkJA4zrA3xUExGm1lDZccw0EnxQhmfMj2TtS66/a25dlZHtrmSe8liOR5cTQJvUpmeYPxyDMOyZn+ps3LCXID8uNSePsBLg458ZuXexwHrVw2nHaen8KCu6BKTXWppGxpBORMdQXE9TtmIkoBdaswoVX6HEcRt0QNEnJRNrGz/NeRXlwTaDU+ZDPoBUdWwzzndxmr3Qw8wCmka33stjeeILubup+NJ7m+fa+Fls/7nK9Y0qFUzypudzyUQ+7hGXCmCUtZ4tat+UoxYa1EVwaXabNTk2w', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=afa6fae6aedac139d298464e08b3191e&lstr=de7aYf08CdQAQGUt%2FL4d%2FgN40W%2B%2Fp%2FCp1dNyAiv12BPDQVsHOIxhVgFOuKW3W6h9DLN%2BrY9ccaOhJFwEHTA&traceid=', 'vcodetype': '4e3dNOQEHLU2Df16LGmwdzdFi XjFHpNh5AT6M23 MKqS25MDIH7PKWqd5 z1gTm2XiYNg2\\/ulCFjQcxlAJKpuH2xl8MGp9Etuxn', 'lstr': 'de7aYf08CdQAQGUt/L4d/gN40W+/p/Cp1dNyAiv12BPDQVsHOIxhVgFOuKW3W6h9DLN+rY9ccaOhJFwEHTA', 'ltoken': 'afa6fae6aedac139d298464e08b3191e', 'realnameverifyemail': '0'}), None
2018-01-16 21:48:49,789 gutil.py :118 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found

2018-01-16 21:48:49,790 SigninDialog.py :97 ERROR SigninVcode.refresh_vcode: None, Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found
.
2018-01-16 21:48:54,667 gutil.py :118 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found

2018-01-16 21:48:54,668 SigninDialog.py :97 ERROR SigninVcode.refresh_vcode: None, Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found
.
2018-01-16 21:49:13,635 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxG7c06c14e0afae2a402a715854301817eafdf980730047b7d', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': '90386Gba1Ys75PZUZh9p4eDaZG0QHUMbOLp++CGToz20hWYLhI6AqHRrX8cMJNZwwYt/RAPoSVqPGJDbXnTj3dwJzMx0mGyHvm3ZbU4aVYv3ivyMON8NTEbCUKD4Bp4Gvl/O2UhVQ35YO/a0PVSkrLLlyjXNZVDxmD47SzZ8B5jDSlfPCS+cbOlRDfq6XJ1nWotXPKvM6wdJdhR5U6RaLbrRklQFiJxca2qC/Ub8Y9ek8MRfery2N4x6+Hp/zdSSlWQZqI6ML2X25WKIJqoHhXLXyUNLGHtSpyxsRgZaFDiN9Z8wYKCSg16IdxwqBFsI9WOUM42EsY3Ju87qxF/6RBDcgfU+qDdvRGovIu4kbsRNogH7IYSjl45BnaFeUpOgxb4FxKn5q8NmC68xbc9wszkRLE4d5vN/wKFUPpcR/yVaADK9n0pu4zF3OoF+cif6Xge1RaCGgZwZ', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=b1e4afaca9c2cede97030d5d36020a46&lstr=6cf5BfL4JaWMdu6ODHsGTToGiSKuJ%2BCBnUnIGUVHdMVVpIm%2BXf8Dk62jnoWeud0UCIZHMLM7qyG2D%2Bw1aWLI&traceid=', 'vcodetype': '9e57STWCQGWAhvffdRzw8dGmAPuwWp TY3\\/6bZ3715pcHgEpmk7NH4iBfhti2nWGo38GPBIz\\/gkonXr43CyocyIOX0hh4yqmdiXi', 'lstr': '6cf5BfL4JaWMdu6ODHsGTToGiSKuJ+CBnUnIGUVHdMVVpIm+Xf8Dk62jnoWeud0UCIZHMLM7qyG2D+w1aWLI', 'ltoken': 'b1e4afaca9c2cede97030d5d36020a46', 'realnameverifyemail': '0'}), None
2018-01-16 21:51:21,894 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxGe107c14e0addc18802f8154f43019f7fb78143074c047e25', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': 'b1a6YDM2R7LORoWRSIyaumgS3lewB4/cyK6++EhlIyoczGqh+7PUYdfzpZNyo9BXDGw+z4afU59gDPDcTOaCKo2zHvKXahq7C81YCucyjvBDwufYFUQquXZaF+ar9qF0eZDtnGscPh4aDmXH7VFgYzdEBLnrQfSNHy4/mdOEsCGlAp8+lMANDYZyJ6vXGSQUSz+HiUzmQEOC3Vm9yfQ6p1KuPxGTzDjuhtrPwQ5cwM46lD4dIyTEEt0tUBpC8xhZtm++AxFmfn65gni+DRg6NHWMT5LHsp/RXsK7PoEe2RHYMxOJ0yUZqZAsi3+21HdQu2SMvH++SWFNLJa8MkGbQyKI93o+ol++aU93zIT9uJjgTiCGnfXdj86g+nCHZsdstKhB5VMsLTYCNFWAyEYCowuNnD4WxoYJjRRoQwZxDn2yZNq2cS6uQRPnaN/sE8wlqLZiEccxE/2S', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=952ea48cd8e09223c66f925081bb6442&lstr=d896EyAFUpLDDuVtRpIa636mOV2w8%2FZKtOm8gf%2Bpx89D1vfhEROxu4vgta9UvvPBNibo83DZZQwxq%2FJW6C06&traceid=', 'vcodetype': '64a0ag\\/\\/bWpGzY 2CNy2ct2r2TMrccZNCc9jB d h5zjvvlN87AWtO11PcFiHn8u8IkOfMbIBqHvK7oJ22AGptumMiKUuZj5SevA', 'lstr': 'd896EyAFUpLDDuVtRpIa636mOV2w8/ZKtOm8gf+px89D1vfhEROxu4vgta9UvvPBNibo83DZZQwxq/JW6C06', 'ltoken': '952ea48cd8e09223c66f925081bb6442', 'realnameverifyemail': '0'}), None
2018-01-16 21:52:03,261 SigninDialog.py :330 ERROR SigninDialog.on_post_login: (4, None), None
2018-01-16 21:52:17,545 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'jxGe606c14e0acfe253024e15074301ac7eba709807a3047b6b', 'userName': '2939921129@qq.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': 'ab3aDQPQGk54ppSdHwR4PFPicsBDAnNa21NzBMSocieyPj7mDdfA7cF7LeQ5hGM3G9YzGBrnpWvqBgf43fOkILd6uim8IwkQ0GLu5KV5NfvzxL8pUvYJzabaCtMW/Lb4zJ8L4puH1mCniwfcutKxJGtyej9FbnH1GrEiMJMb4AhUq7VgxS5Pfh17DxVqk8/xNDA0Qt8GPtbtz7OV3TF4aG6GrZGlWst7igM7uvmX7t1LwPNfnMcQ4pWsPpOC2ylYeUGawmQ40SaJC4fQY7kIpUfojnL7NWpGtBpzQ9wwFIAWG+AJsLxmq/h2nOU/N7El7aisouWl5rjDZ1jLGTX1L5RDa5Sh5wP4ih63CorjC9twvIfmK5Y8FyPR35FQA50ePkExFVceRhkT70y8OqyVxvk6dRfq75JSvNLBoAt5BhY4aze9LfultFPRX+r6Fa2soU9u8+ewq1NelVTitig', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=e32cdda92b910c19591ad89c4bb6cede&lstr=0540xlYCTA2jbSrnfWJ4AHDTMhl9SKxuhPm5KvtnnTg7ue0VV3XuH4TGLOpjzk0S56jwHHpE0GWfN3Gnxht%2F&traceid=', 'vcodetype': '4ca3Xvo7kx3Uu7OApjdCG0VYPkz18yGFv QhiIO\\/OeMf9dsCSpAl4EZVujQQ8obuZwhz3d9P8gCW3mUBkGPm\\/J zntDVYWwdt2 n', 'lstr': '0540xlYCTA2jbSrnfWJ4AHDTMhl9SKxuhPm5KvtnnTg7ue0VV3XuH4TGLOpjzk0S56jwHHpE0GWfN3Gnxht/', 'ltoken': 'e32cdda92b910c19591ad89c4bb6cede', 'realnameverifyemail': '0'}), None
